import json
from typing import Optional, List
from pydantic import Field 
import time
import re

from evoagentx.actions.self_verification import SelfVerificationOutput
from evoagentx.core.logging import logger
from evoagentx.evaluators.evaluator import Evaluator
from ..benchmark.benchmark import Benchmark
from ..core.module import BaseModule
from ..core.message import Message, MessageType
from ..models.base_model import BaseLLM
from ..agents.agent import Agent
from ..agents import AgentManager
from ..agents.task_planner import TaskPlanner
from ..agents.agent_generator import AgentGenerator
from ..agents.meta_controller import MetaController
from ..agents.self_verifier import SelfVerifier
from ..actions.task_planning import TaskPlanningOutput
from ..actions.agent_generation import AgentGenerationOutput
from ..actions.meta_feedback import MetaFeedbackOutput 
from evoagentx.models import OpenAILLMConfig, OpenAILLM, SiliconFlowConfig, SiliconFlowLLM
from ..workflow.workflow_graph import WorkFlowGraph, WorkFlowNode, WorkFlowEdge
from ..workflow import WorkFlow
from ..tools.tool import Toolkit

class MAS_ZERO(BaseModule):
    """
    Multi-Agent System with Zero-shot Task Decomposition and Agent Assignment.

    Attributes:
        llm: Language model used for generation and planning
        task_planner: Component responsible for breaking down goals into subtasks
        agent_generator: Component responsible for agent assignment or creation
        workflow_reviewer: Component for reviewing and improving workflows
        num_turns: Number of refinement iterations for the workflow
    """
    optimizer_llm: BaseLLM = Field(default=None, description="The LLM to use for optimization.")
    executor_llm: BaseLLM = Field(default=None, description="The LLM to use for execution.")
    task_planner: Optional[TaskPlanner] = Field(default=None, description="Responsible for breaking down the high-level task into manageable sub-tasks.")
    agent_generator: Optional[AgentGenerator] = Field(default=None, description="Assigns or generates the appropriate agent(s) to handle each sub-task.")
    meta_controller: Optional[MetaController] = Field(default=None, description="Oversees the evaluation and coordination of multi-agent system iterations.")
    self_verifier: Optional[SelfVerifier] = Field(default=None, description="Validates and verifies the final answers generated by the agents.")
    agent_manager: Optional[AgentManager] = Field(default=None, description="Manages the agents involved in the workflow.")
    tools: Optional[List[Toolkit]] = Field(default=None, description="A list of tools that can be used in the workflow.")

    def init_module(self):
        if self.optimizer_llm is None:
            raise ValueError("optimizer_llm is not provided") 
        else:
            # self.optimizer_llm.init_model()
            self.optimizer_llm = SiliconFlowLLM(config=self.optimizer_llm.config)
            # self.optimizer_llm = OpenAILLM(config=self.optimizer_llm.config)
        
        if self.executor_llm is None:
            self.executor_llm = self.optimizer_llm
        else:
            # self.executor_llm.init_model()
            self.executor_llm = SiliconFlowLLM(config=self.executor_llm.config)
            # self.optimizer_llm = OpenAILLM(config=self.executor_llm.config)
            

        self.task_planner = TaskPlanner(llm=self.executor_llm)
        
        self.agent_generator = AgentGenerator(llm=self.executor_llm, tools=self.tools)

        self.meta_controller = MetaController(llm=self.optimizer_llm)

        self.self_verifier = SelfVerifier(llm=self.optimizer_llm)

        self.agent_manager = AgentManager()


    def get_tool_info(self):
        self.tool_info =[
            {
                tool.name: [
                    s["function"]["description"] for s in (tool.get_tool_schemas() or [])
                ],
            }
            for tool in (self.tools or [])
        ]

    def execute(self, 
            goal: str, 
            existing_agents: Optional[List[Agent]] = None, 
            iteration_num: int = 5) -> str:
        """
        Execute the MAS_ZERO process to achieve the specified goal.
        
        Args:
            goal: The high-level objective to be accomplished.
            evaluator: The evaluator object used for scoring.
            benchmark: The benchmark dataset used for evaluation.
            sample_n: Number of samples used for evaluation.
            existing_agents: Optional list of pre-defined agents to be used in the workflow.
            iteration_num: Number of iterations for refining the workflow and agent assignments.

        Returns:
            final_answer: The best answer selected after self-verification.
            final_score: The evaluation metrics associated with the final answer.
        """

        if not goal or len(goal.strip()) < 10:
            raise ValueError("Goal must be at least 10 characters and descriptive.")
        if iteration_num < 1:
            raise ValueError("`iteration_num` must be a positive integer.")

        self.init_module()
        self.get_tool_info()
        history, suggestion = None, None
        # or_existing_agents = existing_agents if existing_agents else []
        candidate_answers = []
        logger.info(f"Generating workflow for the goal: {goal} | Total iterations: {iteration_num} |Existing agents: {existing_agents}")
        # logger.info(f"Loaded tools: {self.tool_info}")

        for i in range(iteration_num):
            try:
                # logger.info(f"Iteration {i+1}/{iteration_num} — generating workflow for the goal: {goal}...")
                graph = self.generate_workflow(goal=goal, existing_agents=existing_agents, history=history, suggestion=suggestion)

                agent_manager = self.agent_manager
                agent_manager.update_agents_from_workflow(graph, llm_config=self.executor_llm.config)
                workflow = WorkFlow(graph=graph, agent_manager=agent_manager, llm=self.executor_llm, max_execution_steps=10)
        
                # logger.info("Workflow successfully generated. Executing agents...")
                result, added_retries = self._execute_with_retry(
                    operation_name="Executing workflow",
                    operation=workflow.execute,
                    retries_left=2
                )
                # result = workflow.execute()
                candidate_answers.append(result)
                # logger.info(f"Iteration {i+1} completed. Result:\n{result}")

                if i == iteration_num - 1:
                    break  # No need for meta-feedback on the last iteration 

                history = graph.get_workflow_description()
                # suggestion = self.meta_feedback(goal=goal, workflow=workflow)
                suggestion, added_retries = self._execute_with_retry(
                    operation_name="Generating meta-feedback",
                    operation=self.meta_feedback,
                    retries_left=2,
                    goal=goal,
                    workflow=workflow
                )
                # existing_agents = or_existing_agents + agent_manager.agents
                # logger.info(f"History for this iteration: {history}")
                # logger.info(f"Meta-feedback for next iteration: {suggestion}")
            
            except Exception as e:
                logger.warning(f"Iteration {i+1} failed for goal {goal[:50]}... : {e}")
                continue

        if not candidate_answers:
            logger.warning("All iterations failed — no valid candidate answers for self-verification.")
            return "No valid answer generated."

        logger.info("All iterations complete. Proceeding to self-verification...")
        final_answer, added_retries = self._execute_with_retry(
            operation_name="Selecting final answer via self-verification",
            operation=self.self_verification,
            retries_left=1,
            goal=goal,
            candidate_answers=candidate_answers
        )
        # final_answer = self.self_verification(goal=goal, candidate_answers=candidate_answers)
        # logger.info(f"Final answer selected:\n{final_answer}")
        
        return final_answer

    def _execute_with_retry(self, operation_name: str, operation, retries_left: int = 2, **kwargs):
        """Helper method to execute operations with retry logic.
        
        Args:
            operation_name: Name of the operation for logging
            operation: Callable that performs the operation
            retries_left: Number of retry attempts remaining
            **kwargs: Additional arguments to pass to the operation
            
        Returns:
            Tuple of (operation_result, number_of_retries_used)
            
        Raises:
            ValueError: If operation fails after all retries are exhausted
        """
        cur_retries = 0
        # logger.info(f"[DEBUG] executing {operation_name} with kwargs: {kwargs}")
        for k in kwargs.keys():
            if not isinstance(k, str):
                logger.error(f"Non-string key found in kwargs: {repr(k)} (type={type(k)})")

        while cur_retries <= retries_left:  # Changed < to <= to include the initial try
            try:
                logger.info(f"{operation_name} (attempt {cur_retries + 1}/{retries_left + 1}) ...")
                result = operation(**kwargs)
                return result, cur_retries
            except Exception as e:
                if cur_retries == retries_left:
                    raise ValueError(f"Failed to {operation_name} after {cur_retries + 1} attempts.\nError: {e}")
                sleep_time = 2 ** cur_retries
                logger.error(f"Failed to {operation_name} in {cur_retries + 1} attempts. Retry after {sleep_time} seconds.\nError: {e}")
                time.sleep(sleep_time)
                cur_retries += 1
    
    def generate_workflow(self, 
                          goal: str, 
                          existing_agents: Optional[List[Agent]] = None, 
                          history: Optional[str] = None, 
                          suggestion: Optional[str] = None,
                          retry: int = 2, 
                          **kwargs
                          ) -> WorkFlowGraph:

        plan_history = "" if history is None else history
        plan_suggestion = "" if suggestion is None else suggestion

        # Generate the initial workflow plan
        cur_retries = 0
        plan, added_retries = self._execute_with_retry(
            operation_name="Generating a workflow plan",
            operation=self.generate_plan,
            retries_left=retry,
            goal=goal,
            history=plan_history,
            suggestion=plan_suggestion
        )
        cur_retries += added_retries

        # Build workflow from plan
        workflow, added_retries = self._execute_with_retry(
            operation_name="Building workflow from plan",
            operation=self.build_workflow_from_plan,
            retries_left=retry - cur_retries,
            goal=goal,
            plan=plan
        )
        cur_retries += added_retries

        # Validate initial workflow structure
        logger.info("Validating initial workflow structure...")
        workflow._validate_workflow_structure()
        # logger.info(f"Successfully generate the following workflow:\n{workflow.get_workflow_description()}")

        # generate / assigns the initial agents
        # logger.info("Generating agents for the workflow ...")
        workflow, added_retries = self._execute_with_retry(
            operation_name="Generating agents for the workflow",
            operation=self.generate_agents,
            retries_left=retry - cur_retries,
            goal=goal,
            graph=workflow,
            existing_agents=existing_agents,
            history=history,
            suggestion=suggestion
        )

        # Validate workflow after agent generation
        # logger.info("Validating workflow after agent generation...")
        workflow._validate_workflow_structure()
        # Validate that all nodes have agents
        for node in workflow.nodes:
            if not node.agents:
                raise ValueError(f"Node {node.name} has no agents assigned after agent generation")

        return workflow

    def generate_plan(self, 
        goal: str, 
        history: Optional[str] = None, 
        suggestion: Optional[str] = None
    ) -> TaskPlanningOutput:
        
        history = "" if history is None else history
        suggestion = "" if suggestion is None else suggestion
        task_planner: TaskPlanner = self.task_planner
        task_planning_action_data = {"goal": goal, "history": history, "suggestion": suggestion}
        task_planning_action_name = task_planner.task_planning_action_name

        # logger.info(f"[DEBUG] generate_task_plan called with goal type={type(goal)}, history type={type(history)}, suggestion type={type(suggestion)}")
        # action_data = {
        #     "goal": goal,
        #     "history": history or "",
        #     "suggestion": suggestion or "",
        #     }
        # logger.info(f"[DEBUG] action_data keys: {[type(k) for k in action_data.keys()]}")
        # logger.info(f"[DEBUG] action_data content: {action_data}")
        # 重点在这里 —— 如果 action_data 里面有 dict，检查它的键是否都为 str
        # import json
        # def check_dict(d, path="root"):
        #     for k, v in d.items():
        #         if not isinstance(k, str):
        #             logger.error(f"[ERROR] Non-string key detected at {path}: {repr(k)} (type={type(k)})")
        #         if isinstance(v, dict):
        #             check_dict(v, path=f"{path}.{k}")
        # check_dict(action_data)
        message: Message = task_planner.execute(
            action_name=task_planning_action_name,
            action_input_data=task_planning_action_data,
            return_msg_type=MessageType.REQUEST
        ).content

        return message
    
    def generate_agents(
        self, 
        goal: str, 
        graph: WorkFlowGraph,
        existing_agents: Optional[List[Agent]] = None,
        history: Optional[str] = None, 
        suggestion: Optional[str] = None
    ) -> WorkFlowGraph:
        
        history = "" if history is None else history
        suggestion = "" if suggestion is None else suggestion
        existing_agents = [] if existing_agents is None else existing_agents
        agent_generator: AgentGenerator = self.agent_generator
        workflow_desc = graph.get_workflow_description()
        agent_generation_action_name = agent_generator.agent_generation_action_name
        agent_fields = ["name", "description", "inputs", "outputs", "prompt", "tool_names"]
        agents_data = [{key: value for key, value in agent.to_dict(ignore=["class_name"]).items() if key in agent_fields} for agent in existing_agents]
        agents_desc = json.dumps(agents_data, indent=4)
        for subtask in graph.nodes:
            subtask_fields = ["name", "description", "reason", "inputs", "outputs"]
            subtask_data = {key: value for key, value in subtask.to_dict(ignore=["class_name"]).items() if key in subtask_fields}
            subtask_desc = json.dumps(subtask_data, indent=4)
            agent_generation_action_data = {"goal": goal, "workflow": workflow_desc, "task": subtask_desc, "existing_agents": agents_desc, "history": history, "suggestion": suggestion}
            # logger.info(f"Generating agents for subtask: {subtask_data['name']}")
            agents: AgentGenerationOutput = agent_generator.execute(
                action_name=agent_generation_action_name, 
                action_input_data=agent_generation_action_data,
                return_msg_type=MessageType.RESPONSE
            ).content
            # logger.info(f"Raw LLM output before parsing:\n{agents}")

            all_agents = []
            for agent in agents.generated_agents:
                agent_dict = agent.to_dict(ignore=["class_name"])
                all_agents.append(agent_dict)

            for name in agents.selected_agents:
                for agent in existing_agents:
                    if agent.name == name:
                        agent_dict = agent.to_dict(ignore=["class_name"])
                        all_agents.append(agent_dict)
                        break
                else:
                    logger.warning(f"Selected agent {name} not found in existing agents.")
            subtask.set_agents(agents=all_agents)
        
        return graph
    
    def build_workflow_from_plan(self, goal: str, plan: TaskPlanningOutput) -> WorkFlowGraph:
        nodes: List[WorkFlowNode] = plan.sub_tasks
        # infer edges from sub-tasks' inputs and outputs
        edges: List[WorkFlowEdge] = []
        for node in nodes:
            for another_node in nodes:
                if node.name == another_node.name:
                    continue
                node_output_params = [param.name for param in node.outputs]
                another_node_input_params = [param.name for param in another_node.inputs]
                if any([param in another_node_input_params for param in node_output_params]):
                    edges.append(WorkFlowEdge(edge_tuple=(node.name, another_node.name)))
        graph = WorkFlowGraph(goal=goal, nodes=nodes, edges=edges)
        return graph
    
    def meta_feedback(self, goal: str, workflow: WorkFlow) -> MetaFeedbackOutput:
        meta_controller: MetaController = self.meta_controller
        meta_feedback_action_name = meta_controller.meta_feedback_action_name
        workflow_desc = workflow.graph.get_workflow_description()
        suggestion = []

        def get_node_io(workflow: WorkFlow, node_name: str):
            messages = workflow.environment.get_task_messages(tasks=node_name, include_inputs=True)
            inputs = [m.content for m in messages if m.msg_type == MessageType.INPUT]
            outputs = [m.content for m in messages if m.msg_type == MessageType.RESPONSE]
            return inputs, outputs

        def get_agent_io(workflow: WorkFlow, agent_name, task_name=None):
            inputs = []
            outputs = []
            for m in workflow.environment.get():
                if m.agent == agent_name:
                    if task_name is None or m.wf_task == task_name:
                        if m.msg_type == MessageType.INPUT:
                            inputs.append(m.content)
                        elif m.msg_type == MessageType.RESPONSE:
                            outputs.append(m.content)
            return inputs, outputs

        for node in workflow.graph.nodes:
            subtask_level_pairs = []
            agent_level_pairs = []
            for agent in node.agents:
                inputs, outputs = get_agent_io(workflow, agent["name"])
                agent_level_pairs.append({"agent": agent["name"], "inputs": inputs, "outputs": outputs})
            inputs, outputs = get_node_io(workflow, node.name)
            subtask_level_pairs.append({"task": node.name, "inputs": inputs, "outputs": outputs})
            meta_feedback_action_data = {"goal": goal, "workflow": workflow_desc, "subtask_level_pairs": subtask_level_pairs, "agent_level_pairs": agent_level_pairs}
            message: Message = meta_controller.execute(
                action_name=meta_feedback_action_name,
                action_input_data=meta_feedback_action_data,
                return_msg_type=MessageType.REQUEST
            ).content
            suggestion.append(message)
        
        def clean_meta_feedback(suggestion):
            if isinstance(suggestion, list):
                suggestion = [re.sub(r"^```json\s*|\s*```$", "", s.content.strip()) for s in suggestion]
                return "\n\n".join(suggestion)
            return suggestion
        
        final_suggestion = clean_meta_feedback(suggestion)

        return final_suggestion
    
    def self_verification(self, goal: str, candidate_answers: List[str]) -> str:
        if candidate_answers is None:
            raise ValueError("`candidate_answers` to `self_verification` cannot be None")
        # logger.info(f"目前的备选答案有：\n{candidate_answers}...")
        self_verifier: SelfVerifier = self.self_verifier
        self_verification_action_name = self_verifier.self_verification_action_name
        self_verification_action_data = {"goal": goal, "candidate_answers": candidate_answers}
        message: Message = self_verifier.execute(
            action_name=self_verification_action_name,
            action_input_data=self_verification_action_data,
            return_msg_type=MessageType.RESPONSE
        )

        return message.content.final_answer

        def try_parse_json(raw):
            try:
                return json.loads(raw)
            except json.JSONDecodeError:
                # 尝试提取 JSON 部分
                match = re.search(r"\{[\s\S]*\}", raw)
                if match:
                    return json.loads(match.group(0))
                else:
                   # fallback: 包装为 JSON
                    return {
                        "thoughts": "Non-JSON output captured",
                        "final_answer": raw.strip()
                        }
                
        parsed_content = try_parse_json(str(message))

        def safe_parse_json(s: str):
            # 移除Markdown代码块标记
            s = re.sub(r"```[\s\S]*?```", lambda m: m.group(0).replace("```python", "").replace("```", ""), s)
            # 替换小写布尔值
            s = s.replace(" true", " True").replace(" false", " False")
            # 尝试解析
            try:
                return json.loads(s)
            except json.JSONDecodeError as e:
                raise RuntimeError(f"JSON parse failed: {e}\nRaw content:\n{s}")

        final_answer = safe_parse_json(parsed_content["final_answer"])

        return final_answer



