import evoagentx.workflow.operators as operator
import examples.aflow.hotpotqa.optimized.round_12.prompt as prompt_custom
from evoagentx.models.model_configs import LLMConfig
from evoagentx.benchmark.benchmark import Benchmark
from evoagentx.models.model_utils import create_llm_instance

<modification>
# Modification: Add a review and refinement step using the Custom operator to enhance the solution before returning it.
# This will ensure that the solution generated by AnswerGenerate is reviewed and refined for better accuracy and quality.
</modification>

<class Workflow:

    def __init__(
        self,
        name: str,
        llm_config: LLMConfig,
        benchmark: Benchmark
    ):
        self.name = name
        self.llm = create_llm_instance(llm_config)
        self.benchmark = benchmark
        self.custom = operator.Custom(self.llm)
        self.answer_generate = operator.AnswerGenerate(self.llm)
    
    async def __call__(self, problem: str):
        """
        Implementation of the workflow
        """
        # Generate the initial solution
        solution = await self.answer_generate(input=problem)
        answer = solution['answer']
        
        # Review and refine the solution using Custom operator
        refined_solution = await self.custom(input=answer, instruction=prompt_custom.REFINE_PROMPT)
        
        return refined_solution['response']
</graph>

<prompt>
# REFINE_PROMPT = """
# Please review and refine the answer provided. Ensure clarity, correctness, and completeness in your response.
# """
</prompt>
